import os

print("Loading feature data...")
BASE_DIR = os.path.dirname(os.path.abspath(__file__))


def load_top_domains() -> set[str]:
    # Top 500 legit domains taken from https://radar.cloudflare.com/domains
    with open(os.path.join(BASE_DIR, "top_domains.txt"), "r") as f:
        return {line.strip() for line in f.readlines() if line.strip()}


def load_suspicious_words() -> set[str]:
    # Generated by src/gen_sus_words.py
    with open(os.path.join(BASE_DIR, "suspicious_words.txt"), "r") as f:
        return {line.strip() for line in f.readlines() if line.strip()}
