import os

from . import PROJECT_ROOT

BASE_DIR = os.path.join(PROJECT_ROOT, "feature_data")
TOP_DOMAINS = os.path.join(BASE_DIR, "top_domains.txt")
SUSPICIOUS_WORDS = os.path.join(BASE_DIR, "suspicious_words.txt")


def load_lines_as_set(filepath: str, lower: bool) -> set[str]:
    """
    Load the lines of a file into a set, stripping whitespace and optionally converting to lowercase.
    Lines that become empty after stripping are ignored.
    """
    with open(filepath, "r") as f:
        return {
            stripped.lower() if lower else stripped
            for line in f.readlines()
            if (stripped := line.strip())
        }


def load_top_domains() -> set[str]:  # pragma: no cover
    # Top 500 legit domains taken from https://radar.cloudflare.com/domains
    return load_lines_as_set(TOP_DOMAINS, True)


def load_suspicious_words() -> set[str]:  # pragma: no cover
    # Generated by src/gen_sus_words.py
    return load_lines_as_set(SUSPICIOUS_WORDS, True)
